

import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { CircuitService } from '../services/circuit.service';
import * as fabric from 'fabric';
// import { circuitLogicRegistry } from '../circuit-logics';
// import { mainCircuitLogic } from '../circuit-logics' 
import { LineRule, applyRulesToCanvas } from '../rule-engine';


// import { v4 as uuidv4 } from 'uuid';


//this method helps to get the id and name of that particular icon when we save it in file and load it from file
// It adds custom properties to the fabric object so that they can be saved and loaded correctly

function addCustomPropsToObject(obj: fabric.Object) {
  // assign .type and any custom props if missing.
  // For group objects: propagate type, customId, etc. to group level.
  if (obj.type === 'group' || obj.type === 'redSignal' || obj.type === 'redSignalH') {
    if (!('type' in obj) || !(obj as any).type) {
      // If possible, infer from children or set via serialized data
      (obj as any).type = guessTypeFromContent(obj);
    }
    // For your icons, always set .type when constructing AND when deserializing
  }
}

function isRedSignal(obj: fabric.Object): boolean {
  const anyObj = obj as any;
  let type = anyObj.type;
  if (!type || type.toLowerCase() === 'group') {
    type = guessTypeFromContent(obj);
  }
  return type === 'redSignal';
}



function guessTypeFromContent(obj: fabric.Object): string {
  if (obj.type.toLowerCase() === 'group') {
    const children = (obj as any).getObjects?.() ?? [];
    if (children.length === 3 &&
      children.some((o: any) => o.fill === '#8B0000' || o.fill === 'green') &&
      children.some((o: any) => o.fill === 'white')) {
      return 'redSignal';
    }
    return 'group';
  }
  return obj.type || '';
}



function getRandomShortId(length = 3) {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}


@Component({
  selector: 'app-canvas',
  templateUrl: './canvas.component.html',
  styleUrls: ['./canvas.component.css'],
})
export class CanvasComponent implements OnInit {
  @ViewChild('canvas', { static: true }) canvasElement!: ElementRef<HTMLCanvasElement>;
  canvas!: fabric.Canvas;
  deleteZone!: fabric.Rect;
  deleteText!: fabric.Text;

  //Stores loaded circuits and the currently selected one.

  circuits: any[] = [];
  selectedCircuitId: number | null = null;

  // Popup controls UI flags and data for adding icons.

  showIconInputPopup = false;
  inputIconId: string = '';
  inputIconLabel: string = '';
  private iconToAddType: string | null = null;

  // ID counters for autogenerated IDs per icon type
  // Keeps track of auto - increment IDs for each type of icon added.

  private iconIdCounters: Record<string, number> = {
    ground: 0,
    lineR: 0,
    lineG: 0,
    lineB: 0,
    star: 0,
    switch: 0,
    trackjoin: 0,
    redSignal: 0,
    redSignalH: 0,
    diagonalCaution: 0,
    capacitor: 0,
    twocircle: 0,
    triangle: 0,
    zeroShape: 0 // New icon counter

  };

  //For tooltips and tracks number of circuit slots allowed.
  private activeTooltip: fabric.Text | null = null;
  savedCanvasJSONs: string[] = []; // optional backup
  MAX_SLOTS = 3;

  //for text on canvas
  addTextPopupVisible: boolean = false;
  inputTextValue: string = '';
  circuitsRaw: any[] = []; // <-- add this line!




  constructor(private circuitService: CircuitService) { }
  popupVisible: boolean = false;
  popupIcon: fabric.Object | null = null;
  popupType: string = '';
  popupId: string = '';
  popupLabel: string = '';


  //यह map रखेगा की कौन-से redSignal की ID से कौन-सी lines की IDs जुड़ी हैं।
  redSignalLineMap: Record<string, string[]> = {};

  redSignalLineOverrideMap: Record<string, string[]> = {};
  overrideActivatedSignals: Set<string> = new Set();
  overrideRecentlyOpened: Set<string> = new Set();



  // Currently closed signals track करने के लिए set
  private closedSignals: Set<string> = new Set();
  boardRules: LineRule[] = []; 


  // हर line पर affect करने वाले signals का reverse map बनाना होगा
  private linesSignalsMap: Record<string, Set<string>> = {};

  redSignalStateMap: Record<string, 'open' | 'close'> = {}; // id => state

  // Tracks open/close state for close-type red signals (closeHorizontal/closeVertical)
  closeTypeSignalStateMap: Record<string, boolean> = {};

  private selectedCircuitName: string = '';




  // Example: Customize as per circuit design
  private signalToLinesMap: Record<string, string[]> = {
    'CK4': ['YNE', 'LB1'],      // RS1 close होने पर LG1 line affect होगी
    'RS2': ['45V'],             // RS2 close होने पर भी LG1 affect होगी
    'RS1': ['LB1', 'LR1'],      // RS3 का अपना अलग effect
    // Add all your signals and linked lines here
  };


  


  ngOnInit(): void {
    // इस कोड को ngOnInit के सबसे शुरुआत में भी डाल सकते हैं
    fabric.Object.prototype.toObject = (function (toObject) {
      return function (this: fabric.Object, propertiesToInclude?: string[]) {
        propertiesToInclude = (propertiesToInclude || []).concat([
          'permanentId', 'customId', 'customLabel', 'customType', 'originalStroke'
        ]);
        return toObject.call(this, propertiesToInclude);
      };
    })(fabric.Object.prototype.toObject);
    this.circuitService.testBackendConnection().subscribe({
      next: (res) => {
        console.log('✅ Backend connected:', res);
      },
      error: (err) => {
        console.error('❌ Backend connection failed:', err);
      }
    });
    this.circuitService.getDataFromBackend().subscribe({
      next: (data) => {
        if (Array.isArray(data)) {
          this.circuitsRaw = data;
          this.circuits = this.circuitsRaw.map((c: any) => {
            let name = '';
            try {
              const canvasObj = JSON.parse(c.canvasData || c.canvasJson);
              name = canvasObj.name || '';
            } catch (e) {
              console.warn('JSON parse error', e);
            }
            return {
              ...c,
              name
            };
          });
        } else {
          console.error('Data is not array:', data);
          this.circuitsRaw = [];
          this.circuits = [];
        }
      },
      error: (err) => {
        console.error('Error loading circuits:', err);
      }
    });

    this.canvas = new fabric.Canvas(this.canvasElement.nativeElement, {
      width: 3600,
      height: 2200,
      backgroundColor: '#fff',
    });

    this.deleteZone = new fabric.Rect({
      width: 80,
      height: 40,
      left: 1240,
      top: 630,
      fill: 'rgba(255, 0, 0, 0.3)',
      stroke: 'red',
      strokeWidth: 3,
      selectable: true,
      evented: false
    });

    this.deleteText = new fabric.Text('DLT', {
      left: 1257,
      top: 640,
      fontSize: 24,
      fill: 'red',
      selectable: true,
      evented: true
    });

    this.canvas.add(this.deleteZone, this.deleteText);

    this.setupDeleteOnDrop();
    this.setupBuildCompleteIconClick(); // << ✅ नया CALL

    this.canvas.on('mouse:down', (e) => {
      const obj = e.target;
      if (!obj) return;
      const id = (obj as any).permanentId;
      const name = (obj as any).customId;
      console.log('PermanentId:', id, 'CustomId:', name);
      // Tum apna custom game logic bhi yahin laga sakte ho...
    });

    this.redSignalLineMap = {
      // 'RS1,RS2': ['LG1', 'LG7'],
      'RS1,RS2': ['LG2', 'LG3', 'LG5'],
      'RS31': ['LG1', 'LG2', 'LG3', 'LG7'],
      'RS1': ['LG1'],
      'RS2': ['LG2'],
      'RS0': ['LG3'],
      'RS3': ['LG4']

    };

    this.redSignalLineOverrideMap = {
      'RS1,RS3': ['LG7', 'LG8', 'LG11', 'LG12'],
      // 'RS2': ['LG2', 'LG3', 'LG5'],
      'RS5,RS6': ['LG2']
    };

    // signalToLinesMap के आधार पर linesSignalsMap बनाते हैं (reverse map)
    this.rebuildMappingsFromCanvas();
    this.updateLineColors();
    this.loadTemplateLibrary();

    // this.loadFromSlot();
  }

  showAddTextDialog() {
    this.addTextPopupVisible = true;
    this.inputTextValue = '';
  }

  confirmAddText() {
    if (!this.inputTextValue.trim()) return;
    // Create a fabric.Text object, black color, no background.
    const textObj = new fabric.Text(this.inputTextValue, {
      left: 100,
      top: 100,
      fontSize: 24,
      fill: 'black',
      backgroundColor: '', // Transparent
      selectable: true,
      evented: true
    });
    // Custom properties for save/load if needed
    (textObj as any).type = 'canvasText';
    this.canvas.add(textObj);
    this.canvas.renderAll();
    this.addTextPopupVisible = false;
  }



  // =================== Fault Detection State (Feature) ===================
  isFaultDetectionMode: boolean = false;
  faultRedSignals: string[] = [];


  // =================== Fault Detection Feature ===================
  detectFaultMode() {
    this.isFaultDetectionMode = true;
    this.faultRedSignals = ['RS1', 'RS5']; // Example faulty signals
    this.loadFromSlot(2, () => {
      const allRedSignals = this.canvas.getObjects().filter(obj => isRedSignal(obj));
      allRedSignals.forEach(obj => {
        const rsId = (obj as any).customId;
        this.popupIcon = obj;
        this.onRedSignalState('close', true); // Close EVERY signal, skip fault effect!
      });
      this.updateLineColors();
      this.startFaultBlinkEffect();
    });
  }



  // =================== Fault Blink Effect (Fault Detection) ===================
  startFaultBlinkEffect() {
    let blinkCount = 0;
    const blinkLimit = 10; // 3s at 300ms interval
    const canvasBgColors = ['#fff', '#FFD700']; // white/yellow for blink

    const blinkInterval = setInterval(() => {
      this.canvas.backgroundColor = canvasBgColors[blinkCount % 2];
      this.canvas.renderAll();
      blinkCount++;
      if (blinkCount > blinkLimit) {
        clearInterval(blinkInterval);
        this.canvas.backgroundColor = '#fff'; // restore normal
        this.canvas.renderAll();
      }
    }, 300);
  }

  // =================== Visual Fault Effect ===================
  shortCircuitEffectAt(redSignalId: string) {
    const icon = this.canvas.getObjects().find(obj =>
      (obj as any).customId === redSignalId
    );
    if (!icon) return;

    // Flash effect (simple): show yellow "⚡" text near the icon for 1s
    const effect = new fabric.Text('⚡', {
      left: (icon.left || 0) + 20,
      top: (icon.top || 0) - 10,
      fontSize: 24,
      fill: 'yellow',
      selectable: false,
      evented: false,
    });
    this.canvas.add(effect);
    setTimeout(() => {
      this.canvas.remove(effect);
      this.canvas.renderAll();
    }, 1000);
  }

  // Helper to batch close given redSignals using existing popup logic
  closeRedSignalsByIds(ids: string[]) {
    ids.forEach(rsId => {
      const obj = this.canvas.getObjects().find(o => {
        const anyObj = o as any;
        return (
          anyObj.type === 'redSignal'
          || (anyObj.type === 'group' && guessTypeFromContent(o) === 'redSignal')
        ) && anyObj.customId === rsId;
      });
      if (obj) {
        this.popupIcon = obj;
        console.log('Closing redSignal:', rsId, obj); // DEBUG
        this.onRedSignalState('close');
      }
    });
  }



  // Only active when build is “completed”.
  // On click: If you click on an icon, and it’s a redSignal, open popup for setting state.Otherwise, just deselect.


  private isPopupCurrentlyVisible = false;

  setupBuildCompleteIconClick(): void {
    this.canvas.on('mouse:down', (e) => {
      if (!this.isBuildCompleted || this.isPopupCurrentlyVisible) return;

      const pointer = this.canvas.getPointer(e.e);

      for (const obj of this.canvas.getObjects()) {
        if (obj === this.deleteZone || obj === this.deleteText) continue;
        let type = (obj as any).type;
        if (!type || type === 'group') {
          type = guessTypeFromContent(obj);
        }
        if (type !== 'redSignal') continue;

        const bounds = obj.getBoundingRect();

        if (
          pointer.x >= bounds.left &&
          pointer.x <= bounds.left + bounds.width &&
          pointer.y >= bounds.top &&
          pointer.y <= bounds.top + bounds.height
        ) {
          this.isPopupCurrentlyVisible = true;  // Guard flag set kar diya
          this.openPopupForIcon(obj);
          break;
        }
      }
    });
  }

  closePopup() {
    this.popupVisible = false;
    this.isPopupCurrentlyVisible = false;  // Popup close hone par flag reset karo
    this.canvas.discardActiveObject();
    this.canvas.renderAll();
  }

  onlyShowOpenOption: boolean = false;


  // Shows a popup for the redSignal icon.
  // Sets state variables and deselects canvas objects for UI clarity.

  openPopupForIcon(icon: fabric.Object) {
    let type = (icon as any).type || '';
    if (!type || type === 'group') {
      type = guessTypeFromContent(icon);
    }
    if (type !== 'redSignal') return;

    const id = (icon as any).customId || '';
    const label = (icon as any).customLabel || '';
    this.popupVisible = true;
    this.popupIcon = icon;
    this.popupType = type;
    this.popupId = id;
    this.popupLabel = label;
    this.popupVisible = true;
    this.isPopupCurrentlyVisible = true;

    const isCloseType = (label === 'closeHorizontal' || label === 'closeVertical');

    if (isCloseType) {
      // Show Open button if currently closed (false), Close button if open (true)
      this.onlyShowOpenOption = !this.closeTypeSignalStateMap[id];
    } else {
      this.onlyShowOpenOption = this.closedSignals.has(id);
    }

    this.canvas.discardActiveObject();
    this.canvas.renderAll();
  }


  // ================= Popup Logic =================
  openIconInputPopup(iconType: string) {
    if (this.isBuildCompleted) {
      // Ignore or prevent popup from opening since building is completed
      return;
    }
    this.iconToAddType = iconType;
    this.inputIconId = '';
    this.inputIconLabel = '';
    this.showIconInputPopup = true;
  }

  confirmAddIcon() {
    if (!this.iconToAddType) return;
    // Auto-generate ID if left blank
    if (!this.inputIconId.trim()) {
      this.iconIdCounters[this.iconToAddType] = (this.iconIdCounters[this.iconToAddType] || 0) + 1;
      this.inputIconId = this.generateAutoId(this.iconToAddType, this.iconIdCounters[this.iconToAddType]);
    }
    this.addIconToCanvas(this.iconToAddType, this.inputIconId, this.inputIconLabel);
    this.showIconInputPopup = false;
  }


  cancelAddIcon() {
    this.showIconInputPopup = false;
    this.iconToAddType = null;
  }


  generateAutoId(type: string, count: number): string {
    const prefixMap: Record<string, string> = {
      ground: 'GS',
      lineR: 'LR',
      lineG: 'LG',
      lineB: 'LB',
      star: 'ST',
      switch: 'SW',
      trackjoin: 'TJ',
      redSignal: 'RS',
      redSignalH: 'RSH',
      diagonalCaution: 'DC',
      capacitor: 'CP',
      twocircle: 'TC',
      triangle: 'TRI',
      zeroShape: 'CY'  // Add prefix here for zeroShape

    };
    return (prefixMap[type] || 'ID') + count;
  }

  onRedSignalState(state: 'open' | 'close', isAuto: boolean = false) {
    if (!this.popupIcon) {
      this.closePopup();
      return;
    }

    const redSignalId = (this.popupIcon as any).customId || '';
    const label = (this.popupIcon as any).customLabel || '';
    const isCloseType = (label === 'closeHorizontal' || label === 'closeVertical');

    // Check if redSignal is override signal
    const isOverrideRedSignal = Object.keys(this.redSignalLineOverrideMap).some(key =>
      key.split(',').map(s => s.trim()).includes(redSignalId)
    );

    const setSignalState = (angle: number, color: string) => {
      if (!this.popupIcon) return;
      this.popupIcon.set({ angle });
      this.popupIcon.setCoords();
      this.setRedSignalColor(this.popupIcon, color);
      this.canvas.renderAll();
      this.closePopup();
    };

    if (isOverrideRedSignal) {
      const isCloseType = (label === 'closeHorizontal' || label === 'closeVertical');

      if (isCloseType) {
        if (state === 'open') {
          this.closedSignals.delete(redSignalId);
          this.closeTypeSignalStateMap[redSignalId] = true; // open = true
          this.overrideActivatedSignals.delete(redSignalId); // Sync override signals
          setSignalState(90, '#8B0000'); // rotation/color for open
        } else {
          this.closedSignals.add(redSignalId);
          this.closeTypeSignalStateMap[redSignalId] = false; // close = false
          this.overrideActivatedSignals.add(redSignalId);  // Sync override signals
          setSignalState(0, 'green'); // rotation/color for close
        }
      } else {
        // Normal override logic
        if (state === 'close') {
          this.overrideActivatedSignals.add(redSignalId);
          this.closedSignals.add(redSignalId);
          setSignalState(90, 'green');
        } else if (state === 'open') {
          this.overrideActivatedSignals.delete(redSignalId);
          this.closedSignals.delete(redSignalId);
          this.overrideRecentlyOpened.add(redSignalId);
          setSignalState(0, '#8B0000');
          this.overrideRecentlyOpened.delete(redSignalId);
        }
      }

      this.updateLineColors(); // Always update line colors at end
      return;
    }

    if (isCloseType) {
    if (state === 'open') {
        this.closedSignals.delete(redSignalId); // open = not closed
        this.closeTypeSignalStateMap[redSignalId] = true;
        setSignalState(90, '#8B0000'); // open should be red
    } else {
        this.closedSignals.add(redSignalId);
        this.closeTypeSignalStateMap[redSignalId] = false;
        setSignalState(0, 'green'); // close should be green
    }
    this.updateLineColors();
      return;
    }


    // Normal signal logic
    if (state === 'open') {
      this.closedSignals.delete(redSignalId);
      setSignalState(0, '#8B0000');
      this.updateLineColors();
      return;
    }

    if (state === 'close') {
      this.closedSignals.add(redSignalId);
      setSignalState(90, 'green');
      this.updateLineColors();
    }
  }


  // RedSignal ka color change karne wala helper function:
  setRedSignalColor(icon: fabric.Object, color: string) {
    console.log('setRedSignalColor called with type:', (icon as any).type, ', fabric type:', icon.type);
    if ((icon as any).type && icon.type === 'group') {
      // चलो मान लेते हैं कि यह redSignal icon है (या type check आगे ठीक करो)
      const group = icon as fabric.Group;
      group.getObjects().forEach(child => {
        if (child.type === 'rect' && (child.fill === '#8B0000' || child.fill === 'green')) {

          
          console.log('Setting fill:', child.fill, 'to', color);
          child.set('fill', color);
        }
      });
      group.set('dirty', true);
      this.canvas.requestRenderAll();
    } else {
      console.warn('setRedSignalColor: icon not group or type missing');
    }
  }

  // private circuitColorLogicMap: Record<string, () => void> = {
  //   'testing': () => mainCircuitLogic(this.canvas, this.closedSignals),
  //    'corrected the redsignals': () => mainCircuitLogic(this.canvas, this.closedSignals), // Example
  // };


  // private updateLineColors(): void {
  //   const logicFn = this.circuitColorLogicMap[this.selectedCircuitName];
  //   if (logicFn) {
  //     logicFn();
  //    } //else {
  //   //   mainCircuitLogic(this.canvas, this.closedSignals); // Generic fallback
  //   // }
  // }

  private updateLineColors(): void {
  applyRulesToCanvas(this.canvas, this.closedSignals, this.boardRules);
}


  


  private idCounter = 1; // class variable

  addIconToCanvas(type: string, id: string, label: string) {
    let icon: fabric.Object | null = null;
    if (type === 'ground') {
      const line = new fabric.Line([0, 0, 0, 60], { stroke: 'black', strokeWidth: 2, originX: 'center', originY: 'top' });
      const triangle = new fabric.Triangle({ width: 40, height: 20, fill: 'black', left: 0, top: 65, originX: 'center', originY: 'top', angle: 180, selectable: false });
      icon = new fabric.Group([line, triangle], { left: 400, top: 200, hasControls: true, lockScalingFlip: true });
      (icon as any).type = 'ground';
    }
    else if (type === 'lineG' || type === 'lineR' || type === 'lineB') {
      const colorMap: Record<string, string> = { lineR: 'red', lineG: 'green', lineB: 'black' };
      icon = new fabric.Line([400, 100, 550, 100], { stroke: colorMap[type], strokeWidth: 2, selectable: true });
      (icon as any).customId = id;
      (icon as any).customType = type; // <-- Used for easy checks later
      (icon as any).originalStroke = colorMap[type]; // <-- Always store original color
    }

    else if (type === 'star') {
      const diag1 = new fabric.Line([-20, -20, 20, 20], { stroke: 'black', strokeWidth: 6, originX: 'center', originY: 'center' });
      const diag2 = new fabric.Line([20, -20, -20, 20], { stroke: 'black', strokeWidth: 6, originX: 'center', originY: 'center' });
      icon = new fabric.Group([diag1, diag2], { left: 500, top: 200, hasControls: true, lockScalingFlip: true });
      (icon as any).type = 'star';
    } else if (type === 'switch') {
      const leftPath = new fabric.Path('M 0 0 L 16 0 Q 20 -10, 25 -25', {
        stroke: 'black',
        strokeWidth: 6,
        fill: '',
        originX: 'center',
        originY: 'center'
      });
      const rightPath = new fabric.Path('M 0 0 L -16 0 Q -20 10, -25 25', {
        stroke: 'black',
        strokeWidth: 6,
        fill: '',
        originX: 'center',
        originY: 'center'
      });
      leftPath.set({ left: -15 });
      rightPath.set({ left: 15 });
      const whiteMask = new fabric.Ellipse({
        rx: 10,
        ry: 10,
        fill: 'white',
        originX: 'center',
        originY: 'center',
        left: 0,
        top: 0,
        selectable: false,
        evented: false
      });
      icon = new fabric.Group([whiteMask, leftPath, rightPath], {
        left: 600,
        top: 200,
        hasControls: true,
        hasBorders: false,
        selectable: true
      });
      (icon as any).type = 'switch';
    }
    else if (type === 'trackjoin') {
      const line = new fabric.Line([80, 100, 100, 100], { stroke: 'green', strokeWidth: 2, selectable: false });
      const rect1 = new fabric.Rect({ left: 72, top: 90, width: 9, height: 20, fill: 'black', selectable: false });
      const rect2 = new fabric.Rect({ left: 97, top: 90, width: 9, height: 20, fill: 'black', selectable: false });
      const joinLine = new fabric.Line([80, 100, 100, 100], { stroke: 'black', strokeWidth: 9, selectable: false });
      icon = new fabric.Group([line, rect1, rect2, joinLine], { left: 100, top: 100, selectable: true });
      (icon as any).type = 'trackjoin';
    }
    else if (type === 'redSignal') {
      const isVertical = (label === 'vertical' || label === 'closeVertical');
      const isClose = (label === 'closeHorizontal' || label === 'closeVertical');

      // Close types default green, normal types default red
      const fillColor = isClose ? 'green' : '#8B0000';

      let leftRect, rightRect, centerStrip;
      if (!isVertical) {
        leftRect = new fabric.Rect({ width: 10, height: 20, fill: fillColor, left: 86, top: 60, originX: 'center', originY: 'center' });
        rightRect = new fabric.Rect({ width: 10, height: 20, fill: fillColor, left: 101, top: 60, originX: 'center', originY: 'center' });
        centerStrip = new fabric.Rect({ width: 5, height: 22, fill: 'white', left: 93.5, top: 60, originX: 'center', originY: 'center' });
      } else {
        leftRect = new fabric.Rect({ width: 20, height: 10, fill: fillColor, left: 95, top: 86, originX: 'center', originY: 'center' });
        rightRect = new fabric.Rect({ width: 20, height: 10, fill: fillColor, left: 95, top: 101, originX: 'center', originY: 'center' });
        centerStrip = new fabric.Rect({ width: 22, height: 5, fill: 'white', left: 95, top: 93.5, originX: 'center', originY: 'center' });
      }
      icon = new fabric.Group([leftRect, rightRect, centerStrip], {
        left: 600,
        top: 200,
        hasControls: true,
        hasBorders: false,
        selectable: true,
        originX: 'center',
        originY: 'center',
        objectCaching: false,
        angle: 0,
      });

      (icon as any).type = 'redSignal';
      (icon as any).customId = id;
      (icon as any).customOrientation = isVertical ? 'vertical' : 'normal';
      (icon as any).customLabel = label;
      (icon as any).isCloseType = isClose;
    }


    else if (type === 'zeroShape') {
      const points = [
        { x: 50, y: 20 },
        { x: 62, y: 30 },
        { x: 62, y: 50 },
        { x: 50, y: 62 },
        { x: 38, y: 50 },
        { x: 38, y: 30 },
        { x: 50, y: 20 } // close shape
      ];
      icon = new fabric.Polygon(points, {
        left: 460,
        top: 200,
        fill: 'white',
        stroke: 'black',
        strokeWidth: 6,
        selectable: true,
        hasControls: true,
        hasBorders: false,
        originX: 'center',
        originY: 'top'
      });
      (icon as any).type = 'zeroShape';
      // Id aur label yahi assign honge
      (icon as any).customId = id;
      (icon as any).customLabel = label;
    }

    else if (type === 'openSwitch') {
      // Left terminal (circle)
      const leftCircle = new fabric.Circle({
        radius: 10,
        fill: 'white',
        stroke: 'black',
        strokeWidth: 2,
        left: 300,
        top: 200,
        originX: 'center',
        originY: 'center'
      });

      // Right terminal (circle)
      const rightCircle = new fabric.Circle({
        radius: 10,
        fill: 'white',
        stroke: 'black',
        strokeWidth: 2,
        left: 370,
        top: 200,
        originX: 'center',
        originY: 'center'
      });

      // Straight base line (track)
      // const baseLine = new fabric.Line([310, 200, 360, 200], {
      //   stroke: 'black',
      //   strokeWidth: 5,
      //   selectable: false,
      //   evented: false
      // });

      // Switch lever (angled bar)
      const lever = new fabric.Rect({
        left: 310,
        top: 200,
        width: 65,
        height: 5,
        fill: 'black',
        stroke: 'black',
        strokeWidth: 1,
        angle: -25,
        rx: 2,
        ry: 2,
        originX: 'left',
        originY: 'center'
      });

      // Group all parts
      icon = new fabric.Group([leftCircle, rightCircle, lever], {
        left: 340,
        top: 200,
        hasControls: true,
        selectable: true,
        hasBorders: false
      });

      (icon as any).type = 'openSwitch';
      (icon as any).customId = id;
      (icon as any).customLabel = label;
    }


    else if (type === 'redSignalH') {
      const pole = new fabric.Rect({ width: 80, height: 10, fill: 'black', left: 95, top: 60, originX: 'center', originY: 'center' });
      const leftRect = new fabric.Rect({ width: 60, height: 20, fill: '#8B0000', left: 95, top: 47, originX: 'center', originY: 'center' });
      const rightRect = new fabric.Rect({ width: 60, height: 20, fill: '#8B0000', left: 95, top: 73, originX: 'center', originY: 'center' });
      const glow = new fabric.Rect({ width: 60, height: 5, fill: '#fcf9f9ff', left: 95, top: 60, originX: 'center', originY: 'center' });
      icon = new fabric.Group([leftRect, rightRect, pole, glow], { left: 600, top: 200, hasControls: true, hasBorders: false, selectable: true });
      (icon as any).type = 'redSignalH';
    }

    else if (type === 'diagonalCaution') {
      const base = new fabric.Polygon([
        { x: -11, y: -11 },
        { x: 11, y: -11 },
        { x: 11, y: 11 },
        { x: -11, y: 11 }
      ], { fill: '#934bc7ff', originX: 'center', originY: 'center' });
      const stripe = new fabric.Rect({ width: 4, height: 30, fill: '#ffccff', angle: 45, originX: 'center', originY: 'center' });
      icon = new fabric.Group([base, stripe], { left: 600, top: 200, hasControls: true, hasBorders: false, selectable: true });
      (icon as any).type = 'diagonalCaution';
    }
    else if (type === 'capacitor') {
      const bottomPole = new fabric.Rect({ width: 6, height: 20, fill: 'black', top: 30, originX: 'center', originY: 'center' });
      const bottomBar = new fabric.Rect({ width: 40, height: 6, fill: 'black', top: 40, originX: 'center', originY: 'center' });
      const middleWhiteBox = new fabric.Rect({ width: 40, height: 10, fill: 'white', top: 48, originX: 'center', originY: 'center', selectable: false, evented: false });
      const flippedTopBar = new fabric.Rect({ width: 40, height: 6, fill: 'black', top: 56, originX: 'center', originY: 'center' });
      const flippedTopPole = new fabric.Rect({ width: 6, height: 20, fill: 'black', top: 68, originX: 'center', originY: 'center' });
      icon = new fabric.Group([bottomPole, bottomBar, middleWhiteBox, flippedTopBar, flippedTopPole], {
        left: 600,
        top: 200,
        hasControls: true,
        hasBorders: false,
        selectable: true
      });
      (icon as any).type = 'capacitor';
    }
    else if (type === 'twocircle') {
      const whiteBase = new fabric.Circle({ radius: 22, left: 400, top: 200, fill: 'white', selectable: false, evented: false, originX: 'center', originY: 'center' });
      const bigCircle = new fabric.Circle({ radius: 20, left: 400, top: 200, fill: 'white', stroke: 'green', strokeWidth: 2, originX: 'center', originY: 'center' });
      const smallCircle = new fabric.Circle({ radius: 20, left: 400, top: 180, fill: '', stroke: 'red', strokeWidth: 2, originX: 'center', originY: 'center' });
      icon = new fabric.Group([whiteBase, bigCircle, smallCircle], { left: 360, top: 160, hasControls: true, hasBorders: true, selectable: true });
      (icon as any).type = 'twocircle';
    }
    else if (type === 'triangle') {
      const triangle = new fabric.Triangle({
        width: 60,
        height: 45,
        left: 400,
        top: 180,
        fill: 'white',
        stroke: '#e6e3e3ff',
        strokeWidth: 4,
        angle: 0,
        originX: 'center',
        originY: 'top'
      });
      triangle.set({ hasControls: true, hasBorders: true, selectable: true });
      icon = triangle;
      (icon as any).type = 'triangle';
    }
    else {
      alert('Unknown icon type');
      return;
    }
    // You can extend this block for all your other symbols... (see your original symbol creators)

    if (!icon) {
      alert('Unknown icon type');
      return;
    }


    // 3-digit custom permanentId generate करो
    // addIconToCanvas method में
    const shortPermanentId = getRandomShortId(3);
    (icon as any).permanentId = shortPermanentId;

    // --- UUID हर icon को ----------
    (icon as any).permanentId = shortPermanentId;
    (icon as any).customId = id;          // Configurable by user / auto-generated
    (icon as any).customLabel = label;

    (icon as any).customId = id;
    (icon as any).customLabel = label;
    icon.set({ selectable: true, evented: true });
    icon.on('mouseover', () => this.showIconTooltip(icon!));
    icon.on('mouseout', () => this.hideIconTooltip(icon!));
    addCustomPropsToObject(icon);

    this.canvas.add(icon);
    this.canvas.renderAll();
  }

  showAddZeroShapeDialog() {
    this.iconToAddType = 'zeroShape';
    this.inputIconId = ''; // auto-generate id in popup if blank
    this.inputIconLabel = '';
    this.showIconInputPopup = true; // Yeh popup kholta hai jahan user customize kar sakta hai ya blank chod ke auto id milegi
  }

  showAddOpenSwitchDialog() {
    this.iconToAddType = 'openSwitch';
    this.inputIconId = ''; // Auto-generate if blank
    this.inputIconLabel = '';
    this.showIconInputPopup = true;
  }

  private rebuildMappingsFromCanvas() {
    this.signalToLinesMap = { ...this.redSignalLineMap };
    this.linesSignalsMap = {};

    // Initialize with all line keys having empty sets
    this.canvas.getObjects().forEach(obj => {
      const anyObj = obj as any;
      if ((anyObj.customType === 'lineR' || anyObj.customType === 'lineG' || anyObj.customType === 'lineB') && anyObj.customId) {
        if (!this.linesSignalsMap[anyObj.customId]) {
          this.linesSignalsMap[anyObj.customId] = new Set();
        }
      }
    });

    // Build reverse map from signalToLinesMap
    Object.entries(this.signalToLinesMap).forEach(([signalKey, lineIds]) => {
      // Split multi-signal keys
      const signalList = signalKey.split(',');
      lineIds.forEach(lineId => {
        if (!this.linesSignalsMap[lineId]) {
          this.linesSignalsMap[lineId] = new Set();
        }
        signalList.forEach(signal => {
          this.linesSignalsMap[lineId].add(signal.trim());
        });
      });
    });

  }

  //Shows a blue label(like “ID: label”) near the icon on hover.

  showIconTooltip(icon: fabric.Object) {
    this.removeIconTooltip();
    const id = (icon as any).customId || '';
    const label = (icon as any).customLabel || '';
    if (!id && !label) return;
    const tooltipText = label ? `${id}: ${label}` : id;
    this.activeTooltip = new fabric.Text(tooltipText, {
      left: (icon.left || 0) + (icon.width || 0) / 2 + 10,
      top: (icon.top || 0) - 20,
      fontSize: 14,
      fill: 'blue',
      selectable: false,
      evented: false,
    });
    this.canvas.add(this.activeTooltip);
    this.canvas.renderAll();
  }

  hideIconTooltip(icon: fabric.Object) { this.removeIconTooltip(); }
  removeIconTooltip() {
    if (this.activeTooltip) {
      this.canvas.remove(this.activeTooltip);
      this.activeTooltip = null;
      this.canvas.renderAll();
    }
  }

  // ============== Handlers for Icon Add from Button ==============

  //Each symbol has a helper to open the add - icon popup with the correct type.


  showAddGroundIconDialog() { this.openIconInputPopup('ground'); }
  showAddLineRDialog() { this.openIconInputPopup('lineR'); }
  showAddLineGDialog() { this.openIconInputPopup('lineG'); }
  showAddLineBDialog() { this.openIconInputPopup('lineB'); }
  showAddStarDialog() { this.openIconInputPopup('star'); }
  showAddSwitchDialog() { this.openIconInputPopup('switch'); }
  showAddTrackJoinDialog() { this.openIconInputPopup('trackjoin'); }
  showAddRedSignalDialog() {
    const choice = prompt("Choose redsignal type: normal (n), vertical (v), close horizontal (ch), close vertical (cv)?")?.toLowerCase();
    let label = 'normal';
    if (choice === 'v') label = 'vertical';
    else if (choice === 'ch') label = 'closeHorizontal';
    else if (choice === 'cv') label = 'closeVertical';

    // Counter logic
    const count = this.iconIdCounters['redSignal'] || 0;
    const id = this.generateAutoId('redSignal', count);

    this.iconToAddType = 'redSignal';
    this.inputIconId = id;      // Fill the auto-id for convenience
    this.inputIconLabel = label;
    this.showIconInputPopup = true; // Only popup, NO addIconToCanvas here!

    // Counter increment should happen at add (final confirmation) time
  }


  showAddRedSignalHDialog() { this.openIconInputPopup('redSignalH'); }
  showAddDiagonalCautionDialog() { this.openIconInputPopup('diagonalCaution'); }
  showAddCapacitorDialog() { this.openIconInputPopup('capacitor'); }
  showAddTwoCircleDialog() { this.openIconInputPopup('twocircle'); }
  showAddTriangleDialog() { this.openIconInputPopup('triangle'); }
  // Add similar functions for other symbols



  //Switches between “edit” (objects movable) and “build completed” (locked, popups only).
  isBuildCompleted: boolean = false;

  completeCircuitBuild() {
    this.isBuildCompleted = true;
    // Remove delete box & text
    if (this.deleteZone) this.canvas.remove(this.deleteZone);
    if (this.deleteText) this.canvas.remove(this.deleteText);
    this.canvas.getObjects().forEach(obj => {
      if (obj !== this.deleteZone && obj !== this.deleteText) {
        obj.selectable = false;
        obj.evented = false;
      }
    });
    this.canvas.discardActiveObject();
    this.canvas.renderAll();
  }


  editCircuit() {
    this.isBuildCompleted = false;
    // 🔓 Unlock all objects except the delete zone and text
    this.canvas.getObjects().forEach(obj => {
      if (obj !== this.deleteZone && obj !== this.deleteText) {
        obj.selectable = true;
        obj.evented = true;
      }
    });

    // Wapas add karo agar absent hain
    if (!this.canvas.getObjects().includes(this.deleteZone)) {
      this.canvas.add(this.deleteZone);
    }
    if (!this.canvas.getObjects().includes(this.deleteText)) {
      this.canvas.add(this.deleteText);
    }
    this.canvas.renderAll();
  }



  // On dragging icons:
  // Shows current angle as a rotating label while dragging / rotating.
  // Highlights delete zone when icon is over it.
  // On mouse up: removes the icon if dropped in the zone.
  // Resets rotation / angle display after drop.

  setupDeleteOnDrop(): void {
    let rotationText: fabric.Text | null = null;

    this.canvas.on('object:moving', (e) => {
      const obj = e.target;
      if (!obj) return;

      const left = obj.left || 0;
      const top = obj.top || 0;
      const angle = Math.round(obj.angle || 0);

      // 🔄 Show angle text during drag
      if (!rotationText) {
        rotationText = new fabric.Text(`${angle}°`, {
          left: left + obj.width! / 2,
          top: top - 20,
          fontSize: 18,
          fill: 'green',
          selectable: false,
          evented: false,
        });
        this.canvas.add(rotationText);
      } else {
        rotationText.set({
          text: `${angle}°`,
          left: left + obj.width! / 2,
          top: top - 20,
        });
      }

      // 🟥 Check if inside delete zone during move
      if (
        left + obj.width! / 2 > this.deleteZone.left! &&
        left + obj.width! / 2 < this.deleteZone.left! + this.deleteZone.width! &&
        top + obj.height! / 2 > this.deleteZone.top! &&
        top + obj.height! / 2 < this.deleteZone.top! + this.deleteZone.height!
      ) {
        this.deleteZone.set('fill', '#ff0000'); // red
      } else {
        this.deleteZone.set('fill', '#ddd'); // default
      }

      this.canvas.renderAll();
    });

    // 🔄 Also show rotation angle during rotation
    this.canvas.on('object:rotating', (e) => {
      const obj = e.target;
      if (!obj) return;

      const angle = Math.round(obj.angle || 0);
      const left = obj.left || 0;
      const top = obj.top || 0;

      if (!rotationText) {
        rotationText = new fabric.Text(`${angle}°`, {
          left: left + obj.width! / 2,
          top: top - 20,
          fontSize: 18,
          fill: 'green',
          selectable: false,
          evented: false,
        });
        this.canvas.add(rotationText);
      } else {
        rotationText.set({
          text: `${angle}°`,
          left: left + obj.width! / 2,
          top: top - 20,
        });
      }

      this.canvas.renderAll();
    });

    this.canvas.on('mouse:up', (e) => {
      const obj = e.target;
      if (!obj) return;

      const left = obj.left || 0;
      const top = obj.top || 0;

      // ✅ Final delete if dropped in zone
      if (
        left + obj.width! / 2 > this.deleteZone.left! &&
        left + obj.width! / 2 < this.deleteZone.left! + this.deleteZone.width! &&
        top + obj.height! / 2 > this.deleteZone.top! &&
        top + obj.height! / 2 < this.deleteZone.top! + this.deleteZone.height!
      ) {
        this.canvas.remove(obj);
        this.removeIconTooltip();  // Tooltip ko bhi remove karo jab icon delete ho
      }

      // 🔄 Reset delete zone fill
      this.deleteZone.set('fill', '#ddd');

      // ❌ Remove angle display
      if (rotationText) {
        this.canvas.remove(rotationText);
        rotationText = null;
      }

      this.canvas.renderAll();
    });
  }

  // Helper to check overlap
  // Helper for collision between icon and delete zone.


  isOverDeleteZone(obj: fabric.Object): boolean {
    if (!this.deleteZone) return false;

    const objBounds = obj.getBoundingRect();
    const zoneBounds = this.deleteZone.getBoundingRect();

    // Simple rectangle intersection formula
    const overlap = !(
      objBounds.left > zoneBounds.left + zoneBounds.width ||
      objBounds.left + objBounds.width < zoneBounds.left ||
      objBounds.top > zoneBounds.top + zoneBounds.height ||
      objBounds.top + objBounds.height < zoneBounds.top
    );
    return overlap;
  }

  onCircuitSelect() {
    if (this.selectedCircuitId == null) return; // Guard: only proceed if it's NOT null

    const selected = this.circuits.find(c => c.id === Number(this.selectedCircuitId));
    if (selected) {
      this.loadCanvasFromJson(selected.canvasJson || selected.canvasData);
    }
  }

  async loadCanvasFromJson(json: string) {
    if (!json) return;
    this.clearCanvas();

    // Standard expected format: full circuit object (not just array)
    const data = typeof json === 'string' ? JSON.parse(json) : json;
    this.selectedCircuitName = data.name || ''; // <-- SET here

    console.log('loadCanvasFromJson data:', data);

    const objectsArray = data.objects || []; // fallback
    // Restore mappings and signal states
    this.redSignalLineMap = data.redSignalLineMap || {};
    this.redSignalLineOverrideMap = data.redSignalLineOverrideMap; // ADD THIS

    this.closedSignals = new Set(data.closedSignalsArray || []);
    this.boardRules = data.rules || [];


    // console.log('redSignalLineMap:', this.redSignalLineMap);
    // console.log('redSignalLineOverrideMap:', this.redSignalLineOverrideMap);
    // console.log('closedSignals:', Array.from(this.closedSignals));


    const enlivenedObjects: fabric.Object[] = await fabric.util.enlivenObjects(objectsArray);
    enlivenedObjects.forEach(obj => {
      if (obj instanceof fabric.Object) {
        const anyObj = obj as any;
        anyObj.customId = anyObj.customId;
        anyObj.customLabel = anyObj.customLabel;
        anyObj.customType = anyObj.customType;
        obj.type = anyObj.type;
        // Tooltip events agar required ho to
        (obj as fabric.Object).on('mouseover', this.showIconTooltip.bind(this, obj));
        (obj as fabric.Object).on('mouseout', this.hideIconTooltip.bind(this, obj));
        this.canvas.add(obj);
      }
      this.canvas.getObjects().forEach(obj => {
        if ((obj as any).type === 'rect' && (obj.left === 1240 && obj.top === 630)) {
          this.canvas.remove(obj); // fix for dlt zone, use suitable property checks
        }
        if ((obj as fabric.Text).text === 'DLT') {
          this.canvas.remove(obj);
        }
      });
    });


    // Static UI
    this.canvas.add(this.deleteZone, this.deleteText);

    // Restore line/signal mapping/colors if needed
    this.rebuildMappingsFromCanvas();
    this.updateLineColors();

    this.canvas.renderAll();
    this.loadRulesFromDb();
  }


  //Saves canvas data from a slot as a JSON file via download.
  exportSlotToFile(slot: number): void {
    const dataStr = localStorage.getItem(`circuit_slot_${slot}`);
    if (!dataStr) {
      alert(`❌ No data found in Slot ${slot + 1}`);
      return;
    }
    const data = JSON.parse(dataStr);
    const fileName = data.name ? `${data.name}.json` : `circuit_slot_${slot + 1}.json`;
    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  }
   
  loadRulesFromDb() {
  if (!this.selectedCircuitName) { this.boardRules = []; this.updateLineColors(); return; }
  this.circuitService.getRulesByName(this.selectedCircuitName).subscribe({
    next: (rows) => {
      this.boardRules = (rows || []).map((r: any) => ({
        id: r.id,
        when: r.whenCondition,
        lines: (r.linesCsv || '').split(',').map((s: string) => s.trim()).filter(Boolean),
        stroke: r.stroke || 'red',
        priority: r.priority || 1
      }));
      this.updateLineColors();
    },
    error: (e) => { console.error('Rules load fail', e); this.boardRules = []; }
  });
}



  //Loads circuit data from a file, validates, and saves it to a slot.
  importFileToSlot(event: Event, slot: number): void {
    const input = event.target as HTMLInputElement;
    if (!input.files || input.files.length === 0) {
      alert('❌ No file selected');
      return;
    }

    const file = input.files[0];
    const reader = new FileReader();

    reader.onload = () => {
      try {
        const jsonString = reader.result as string;

        // Validate JSON
        const parsed = JSON.parse(jsonString);

        // Optional: Validate it's an array of fabric objects
        if (!parsed.objects || !Array.isArray(parsed.objects)) {
          throw new Error("Invalid format: missing objects array");
        }


        // Save to slot
        localStorage.setItem(`circuit_slot_${slot}`, jsonString);
        alert(`✅ File imported and saved to Slot ${slot + 1}`);
      } catch (e) {
        alert('❌ Invalid circuit file');
      }
    };

    reader.readAsText(file);
  }

  //To save 3 circuits on UI

  // savedCanvasJSONs: string[] = []; // optional in-memory backup
  // MAX_SLOTS = 3;

  // ✅ SAVE to a slot (0, 1, 2)


  circuitNamePopupVisible = false;
  inputCircuitName = '';
  saveSlotPending = -1;



  // Saves the current canvas(except delete objects) as a JSON in a slot and also to the backend.
  // Save the current canvas (except delete objects) as a JSON in a slot and also to the backend.
  saveToSlot(slot: number): void {
    if (this.circuitNamePopupVisible) return; // prevent multiple popups

    const existingData = localStorage.getItem(`circuit_slot_${slot}`);
    if (existingData) {
      alert(`❗Slot ${slot + 1} already has a saved circuit.\nPlease delete it first before saving a new one.`);
      return; // Popup nahi dikhana agar slot full hai
    }

    this.saveSlotPending = slot;
    this.inputCircuitName = '';
    this.circuitNamePopupVisible = true;  // Popup tabhi dikhao jab slot free ho
  }


  confirmSaveCircuit() {
  const slot = this.saveSlotPending;
  const name = this.inputCircuitName.trim();

  if (!name) { alert('Circuit name cannot be empty.'); return; }

  const existingData = localStorage.getItem(`circuit_slot_${slot}`);
  if (existingData) {
    alert(`❗Slot ${slot + 1} already has a saved circuit.\nPlease delete it first.`);
    this.circuitNamePopupVisible = false;
    this.saveSlotPending = -1;
    return;
  }

  const objectsToSave = this.canvas.getObjects().filter(obj =>
    obj !== this.deleteZone && obj !== this.deleteText
  );
  const jsonObjects = objectsToSave.map(obj => obj.toObject());

  const saveData = {
    name,
    objects: jsonObjects,
    redSignalLineMap: this.redSignalLineMap,
    redSignalLineOverrideMap: this.redSignalLineOverrideMap,
    closedSignalsArray: Array.from(this.closedSignals),
  };

  localStorage.setItem(`circuit_slot_${slot}`, JSON.stringify(saveData));

  this.circuitService.saveCircuit(saveData).subscribe({
    next: (response) => {
      console.log('✅ circuit saved in canvas_data. Ab rules DB me daal raha hoon...');
      this.persistRulesForName(name);   // <-- YAHIN rules naam ke saath DB me jaate hain
      alert(`Circuit saved as "${name}"`);
      this.circuitNamePopupVisible = false;
      this.saveSlotPending = -1;
    },
    error: (error) => {
      alert('❌ Error saving circuit to backend, but data saved locally.');
      console.error('Error saving circuit:', error);
    }
  });
}

  private persistRulesForName(name: string) {
  console.log('💾 persistRulesForName CALLED. name =', name, '| boardRules count =', this.boardRules.length);
  if (!name) { console.warn('⚠️ name khaali, skip'); return; }

  // purane rules hatane ki koshish — agar method/endpoint na ho to bhi create CHALEGA
  const svc: any = this.circuitService;
  if (typeof svc.deleteRulesByName === 'function') {
    svc.deleteRulesByName(name).subscribe({
      next: () => this.createAllRules(name),
      error: () => this.createAllRules(name)   // delete fail ho to bhi create karo
    });
  } else {
    console.warn('⚠️ deleteRulesByName service me nahi — seedha create kar raha hoon');
    this.createAllRules(name);
  }
}

private createAllRules(name: string) {
  if (!this.boardRules.length) {
    console.warn('⚠️ boardRules KHAALI hai — kuch save nahi hoga. Pehle rule add karo, phir save.');
    return;
  }
  this.boardRules.forEach(r => {
    const payload = {
      circuitName: name,                 // <-- NAAM yahin jaata hai
      whenCondition: r.when,
      linesCsv: r.lines.join(','),
      stroke: r.stroke || 'red',
      priority: r.priority || 1
    };
    console.log('➕ creating rule payload:', payload);
    this.circuitService.createRule(payload).subscribe({
      next: (saved: any) => { r.id = saved?.id; console.log('✅ rule saved, id =', saved?.id); },
      error: (e) => console.error('❌ rule save FAIL:', e)
    });
  });
}


  // Load JSON from a slot, reconstruct objects using Fabric's enlivenObjects and restore signal states.
  loadFromSlot(slot: number, afterLoadCallback?: () => void): void {
    const data = localStorage.getItem(`circuit_slot_${slot}`);
    if (!data) {
      alert(`❌ No circuit saved in Slot ${slot + 1}`);
      return;
    }

    this.clearCanvas();

    const parsed = JSON.parse(data);

    this.redSignalLineMap = parsed.redSignalLineMap || {};
    this.redSignalLineOverrideMap = parsed.redSignalLineOverrideMap || {};   // <-- Yeh bhi restore karo

    this.closedSignals = new Set(parsed.closedSignalsArray || []);
    // this.boardRules = parsed.rules || [];
        this.boardRules = [];   

    fabric.util.enlivenObjects(parsed.objects).then((enlivenedObjects) => {
      enlivenedObjects.forEach(obj => {
        if (obj instanceof fabric.Object) {
          const anyObj = obj as any;
          anyObj.customId = anyObj.customId || '';
          anyObj.customLabel = anyObj.customLabel || '';
          anyObj.customType = anyObj.customType || obj.type || '';

          const fabricObj = obj as fabric.Object & { on: (event: string, handler: (e?: any) => void) => void };
          fabricObj.on('mouseover', () => this.showIconTooltip(obj));
          fabricObj.on('mouseout', () => this.hideIconTooltip(obj));

          this.canvas.add(obj);
        }
      });

      // Rebuild signal and line mappings dynamically
      this.rebuildMappingsFromCanvas();

      // Update colors of lines using closedSignals set
      this.updateLineColors();

      this.canvas.renderAll();
      if (afterLoadCallback) afterLoadCallback();

    }).catch(err => {
      console.error('Error loading canvas:', err);
      alert('❌ Failed to load circuit');
    });
  }


  updateLineColorsForRedSignal(redSignalId: string, makeRed: boolean) {
    const lineIds = this.redSignalLineMap[redSignalId] || [];
    this.canvas.getObjects().forEach(obj => {
      if ((obj as any).customId && lineIds.includes((obj as any).customId)) {
        const type = (obj as any).customType;
        // Only process green and red lines, ignore black lines
        if (type === 'lineG' || type === 'lineR') {
          if (makeRed) {
            obj.set('stroke', 'red');
          } else {
            // Restore to original color
            obj.set('stroke', (obj as any).originalStroke || 'green');
          }
        }
        // Black lineB ignored
      }
    });
    this.canvas.renderAll();
  }



  // Removes data for a slot from local storage and clears the canvas.

  deleteSlot(slotNumber: number): void {
    localStorage.removeItem(`circuit_slot_${slotNumber}`); // 🔁 key name fix
    this.clearCanvas(); // 👈 Clear canvas when deleted
    alert(`🗑️ Circuit ${slotNumber + 1} deleted.`);
  }


  // Shows or removes an angle label for rotated icons.


  updateRotationLabel(obj: fabric.Object) {
    this.removeAngleLabels();

    const angle = obj.angle || 0;

    const angleLabel = new fabric.Text(`${Math.round(angle)}°`, {
      left: obj.left! + (obj.width || 0) / 2 + 10,
      top: obj.top! - 10,
      fontSize: 14,
      fill: 'blue',
      selectable: false,
      evented: false,
    }) as fabric.Text & { name: string };

    angleLabel.name = 'angleLabel';
    this.canvas.add(angleLabel);
    this.canvas.renderAll();
  }

  removeAngleLabels() {
    const labels = this.canvas.getObjects('text').filter(obj => (obj as any).name === 'angleLabel');
    labels.forEach(label => this.canvas.remove(label));
  }


  // Zoom in/out of the canvas.
  zoomIn() {
    this.canvas.setZoom(this.canvas.getZoom() * 1.1);
  }

  zoomOut() {
    this.canvas.setZoom(this.canvas.getZoom() / 1.1);
  }


  // ClearCanvas: Removes everything except deleteZone and deleteText.
  clearCanvas(): void {
    const objectsToPreserve = [this.deleteZone, this.deleteText];
    this.canvas.getObjects().forEach((obj: fabric.Object) => {
      if (!objectsToPreserve.some(o => o === obj)) {
        this.canvas.remove(obj);
      }
    });
    this.canvas.renderAll();
  }

  // ===================== COPY / PASTE SECTION =====================

  copiedSection: any[] = [];
  showPasteOffsetDialog = false;
  pasteOffsetX = 400;
  pasteOffsetY = 0;

  copySelectedSection() {
    const activeObjects = this.canvas.getActiveObjects();
    if (activeObjects.length === 0) {
      alert('No objects selected. First select objects on canvas (use Shift+click or drag to multi-select), then click Copy Selected Section.');
      return;
    }

    // CRITICAL: Fabric.js multi-select me objects ki left/top coordinates
    // ActiveSelection group ke center se relative hoti hain, absolute nahi.
    // discardActiveObject() call karne se sab objects apni absolute canvas
    // coordinates restore kar lete hain before we serialize them.
    this.canvas.discardActiveObject();
    this.canvas.renderAll();

    this.copiedSection = activeObjects.map(obj =>
      obj.toObject(['permanentId', 'customId', 'customLabel', 'customType', 'originalStroke'])
    );
    alert(`✅ ${activeObjects.length} objects copied successfully!`);
  }

  openPasteDialog() {
    if (this.copiedSection.length === 0) {
      alert('No section copied. Please copy a section first using Copy Selected Section.');
      return;
    }
    this.showPasteOffsetDialog = true;
  }

  async confirmPasteSection() {
    this.showPasteOffsetDialog = false;
    const enlivened: fabric.Object[] = await fabric.util.enlivenObjects(this.copiedSection);
    enlivened.forEach(obj => {
      obj.set({
        left: (obj.left || 0) + this.pasteOffsetX,
        top: (obj.top || 0) + this.pasteOffsetY,
      });
      (obj as any).permanentId = getRandomShortId(3);
      obj.on('mouseover', () => this.showIconTooltip(obj));
      obj.on('mouseout', () => this.hideIconTooltip(obj));
      this.canvas.add(obj);
    });
    this.canvas.renderAll();
    alert(`✅ ${enlivened.length} objects pasted successfully! Use Smart Rename Manager to update IDs.`);
  }

  // ===================== BULK ID RENAME (General) =====================

  showBulkRenamePanel = false;
  bulkFindText = '';
  bulkReplaceText = '';

  applyBulkRename() {
    if (!this.bulkFindText.trim()) {
      alert('Find field is empty. Please enter a value to search for.');
      return;
    }
    const escapedFind = this.bulkFindText.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(escapedFind, 'g');
    let count = 0;

    this.canvas.getObjects().forEach(obj => {
      const anyObj = obj as any;
      if (anyObj.customId && anyObj.customId.includes(this.bulkFindText)) {
        anyObj.customId = anyObj.customId.replace(regex, this.bulkReplaceText);
        count++;
      }
      if ((obj.type === 'text' || obj.type === 'i-text') && (obj as any).text) {
        const textObj = obj as fabric.Text;
        if (textObj.text && textObj.text.includes(this.bulkFindText)) {
          textObj.set('text', textObj.text.replace(new RegExp(escapedFind, 'g'), this.bulkReplaceText));
          count++;
        }
      }
    });

    this.canvas.renderAll();
    alert(`✅ ${count} IDs/texts updated!`);
    this.bulkFindText = '';
    this.bulkReplaceText = '';
  }

  // ===================== SMART RENAME MANAGER =====================

  showRenameManager = false;

  bmFindText = '';
  bmReplaceText = '';

  lineFindText = '';
  lineReplaceText = '';

  rsFindText = '';
  rsReplaceText = '';

  private escapeRegex(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  // Canvas Text objects update karta hai (BM labels like "BM524")
  // Handles two formats:
  //   1. Single text: "BM711" as one object  → direct replace
  //   2. Split text:  "BM" + "711" as two separate objects → number-part replace
  applyBMRename() {
    if (!this.bmFindText.trim()) { alert('Find field is empty. Please enter a value to search for.'); return; }

    const findText  = this.bmFindText.trim();
    const replText  = this.bmReplaceText.trim();
    const regex     = new RegExp(this.escapeRegex(findText), 'g');

    // Extract letter-prefix and number-suffix from both find and replace.
    // e.g. "BM711" → prefix="BM", numPart="711"
    //      "CB1089" → prefix="CB", numPart="1089"
    const splitPattern = /^([A-Za-z]+)(\d+[A-Za-z0-9]*)$/;
    const findSplit  = findText.match(splitPattern);
    const replSplit  = replText.match(splitPattern);

    // numericFind/numericReplace only used when both sides have same letter-prefix
    // e.g. BM711→BM729 extracts "711"→"729"; CB711→BM711 would NOT trigger split mode
    const samePrefix = findSplit && replSplit && findSplit[1] === replSplit[1];
    const numericFind    = samePrefix ? findSplit![2] : null;  // "711"
    const numericReplace = samePrefix ? replSplit![2] : null;  // "729"

    let count = 0;
    this.canvas.getObjects().forEach(obj => {
      if (!(obj instanceof fabric.Text)) return;
      const t = obj as fabric.Text;
      if (!t.text) return;

      const trimmed = t.text.trim();

      if (trimmed.includes(findText)) {
        // Format 1: single object contains full label like "BM711"
        t.set('text', t.text.replace(regex, replText));
        count++;
      } else if (numericFind && trimmed === numericFind) {
        // Format 2: split layout — this object is just the number "711"
        // Replace the whole text content with the new number "729"
        t.set('text', numericReplace!);
        count++;
      }
    });

    this.canvas.renderAll();
    alert(`✅ ${count} BM text label(s) updated!`);
    this.bmFindText  = '';
    this.bmReplaceText = '';
  }

  // Sirf Line objects (lineG / lineR / lineB) ke customId
  applyLineRename() {
    if (!this.lineFindText.trim()) { alert('Find field is empty. Please enter a value to search for.'); return; }
    const regex = new RegExp(this.escapeRegex(this.lineFindText), 'g');
    let count = 0;
    this.canvas.getObjects().forEach(obj => {
      const a = obj as any;
      if (['lineG', 'lineR', 'lineB'].includes(a.customType) && a.customId && a.customId.includes(this.lineFindText)) {
        a.customId = a.customId.replace(regex, this.lineReplaceText);
        count++;
      }
    });
    this.canvas.renderAll();
    alert(`✅ ${count} Line IDs updated!`);
    this.lineFindText = '';
    this.lineReplaceText = '';
  }

  // Sirf RedSignal objects ke customId (RS values)
  applyRSRename() {
    if (!this.rsFindText.trim()) { alert('Find field is empty. Please enter a value to search for.'); return; }
    const regex = new RegExp(this.escapeRegex(this.rsFindText), 'g');
    let count = 0;
    this.canvas.getObjects().forEach(obj => {
      const a = obj as any;
      // Use isRedSignal() which correctly handles both fresh objects (type='redSignal')
      // and loaded objects (Fabric sets type='group', so we must guess from children).
      // Old check: a.type || guessTypeFromContent() — 'group' is truthy so guess never ran.
      if (isRedSignal(obj) && a.customId && a.customId.includes(this.rsFindText)) {
        a.customId = a.customId.replace(regex, this.rsReplaceText);
        count++;
      }
    });
    this.canvas.renderAll();
    alert(`✅ ${count} RS value(s) updated!`);
    this.rsFindText = '';
    this.rsReplaceText = '';
  }

  // ===================== TEMPLATE LIBRARY =====================

  templateLibrary: { name: string; objects: any[]; objectCount: number }[] = [];
  showTemplateLibrary = false;
  showSaveTemplateDialog = false;
  inputTemplateName = '';

  loadTemplateLibrary() {
    try {
      this.templateLibrary = JSON.parse(localStorage.getItem('section_templates') || '[]');
    } catch {
      this.templateLibrary = [];
    }
  }

  openSaveTemplateDialog() {
    if (this.copiedSection.length === 0) {
      alert('No section copied. Please select objects and click Copy Selected Section first.');
      return;
    }
    this.inputTemplateName = '';
    this.showSaveTemplateDialog = true;
  }

  confirmSaveTemplate() {
    const name = this.inputTemplateName.trim();
    if (!name) { alert('Template name cannot be empty.'); return; }
    const duplicate = this.templateLibrary.find(t => t.name === name);
    if (duplicate) {
      alert(`A template named "${name}" already exists. Please choose a different name.`);
      return;
    }

    // Normalize: saare objects ki positions ko (0,0) se start karwao.
    // Isse template kisi bhi canvas pe pasteOffsetX/Y se sahi jagah load hoga.
    const objs = this.copiedSection as any[];
    const minX = Math.min(...objs.map(o => o.left ?? 0));
    const minY = Math.min(...objs.map(o => o.top ?? 0));
    const normalized = objs.map(o => ({ ...o, left: (o.left ?? 0) - minX, top: (o.top ?? 0) - minY }));

    this.templateLibrary.push({ name, objects: normalized, objectCount: normalized.length });
    localStorage.setItem('section_templates', JSON.stringify(this.templateLibrary));
    this.showSaveTemplateDialog = false;
    alert(`✅ Template "${name}" saved successfully! (${normalized.length} objects)`);
  }

  async loadTemplate(index: number) {
    const template = this.templateLibrary[index];
    if (!template) return;
    const enlivened: fabric.Object[] = await fabric.util.enlivenObjects(template.objects);
    enlivened.forEach(obj => {
      obj.set({
        left: (obj.left || 0) + this.pasteOffsetX,
        top: (obj.top || 0) + this.pasteOffsetY,
      });
      (obj as any).permanentId = getRandomShortId(3);
      obj.on('mouseover', () => this.showIconTooltip(obj));
      obj.on('mouseout', () => this.hideIconTooltip(obj));
      this.canvas.add(obj);
    });
    this.canvas.renderAll();
    alert(`✅ "${template.name}" loaded successfully! Use Smart Rename Manager to update IDs.`);
  }

  deleteTemplate(index: number) {
    const name = this.templateLibrary[index].name;
    if (!confirm(`Are you sure you want to permanently delete the template "${name}"?`)) return;
    this.templateLibrary.splice(index, 1);
    localStorage.setItem('section_templates', JSON.stringify(this.templateLibrary));
  }

  exportTemplateLibrary() {
    if (this.templateLibrary.length === 0) {
      alert('Template library is empty. Save at least one template before exporting.');
      return;
    }
    const blob = new Blob([JSON.stringify(this.templateLibrary, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'section_templates.json';
    a.click();
    URL.revokeObjectURL(url);
  }

  importTemplateLibrary(event: Event) {
    const input = event.target as HTMLInputElement;
    if (!input.files || input.files.length === 0) return;
    const reader = new FileReader();
    reader.onload = () => {
      try {
        const imported: { name: string; objects: any[]; objectCount: number }[] = JSON.parse(reader.result as string);
        if (!Array.isArray(imported)) throw new Error('Invalid format');
        let added = 0;
        imported.forEach(t => {
          if (!this.templateLibrary.find(existing => existing.name === t.name)) {
            this.templateLibrary.push(t);
            added++;
          }
        });
        localStorage.setItem('section_templates', JSON.stringify(this.templateLibrary));
        alert(`✅ ${added} new templates imported successfully!`);
      } catch {
        alert('❌ Invalid template file');
      }
    };
    reader.readAsText(input.files[0]);
    input.value = '';
  }
  
// ===== Rule Builder =====
showRuleBuilder = false;
showRulesManager = false;   // <-- NEW: rules list popup
ruleLines = '';
ruleWhen = '';
rulePriority = 1;
editingRuleIndex: number | null = null;

openRuleBuilder() {
  this.editingRuleIndex = null;
  this.ruleLines = '';
  this.ruleWhen = '';
  this.rulePriority = 1;
  this.showRulesManager = false;   // manager band karo
  this.showRuleBuilder = true;
}

openRulesManager() {               // <-- NEW
  this.showRulesManager = true;
}

editRule(i: number) {
  const r = this.boardRules[i];
  this.editingRuleIndex = i;
  this.ruleLines = r.lines.join(', ');
  this.ruleWhen = r.when;
  this.rulePriority = r.priority;
  this.showRulesManager = false;   // manager band
  this.showRuleBuilder = true;     // builder kholo
}

private getCanvasIds(prefix: string): string[] {
  return this.canvas.getObjects()
    .map(o => (o as any).customId)
    .filter(id => typeof id === 'string' && id.startsWith(prefix));
}

addRule() {
  const lines = this.ruleLines.split(',').map(s => s.trim().toUpperCase()).filter(Boolean);
  const when = this.ruleWhen.trim().toUpperCase();
  if (!lines.length || !when) { alert('Need Lines and Conditions'); return; }

  const availRS = new Set(this.getCanvasIds('RS'));
  const availLG = new Set(this.getCanvasIds('LG'));
  const usedRS = when.match(/RS\w+/g) || [];
  const badRS = usedRS.filter(rs => !availRS.has(rs));
  const badLG = lines.filter(lg => !availLG.has(lg));
  if (badRS.length) { alert('This RS is not related to this board: ' + badRS.join(', ')); return; }
  if (badLG.length) { alert('This LG is not related to this board: ' + badLG.join(', ')); return; }

  if (this.editingRuleIndex !== null) {
    this.boardRules[this.editingRuleIndex] = { when, lines, stroke: 'red', priority: this.rulePriority || 1 };
    this.editingRuleIndex = null;
  } else {
    this.boardRules.push({ when, lines, stroke: 'red', priority: this.rulePriority || 1 });
  }
  this.showRuleBuilder = false;
  this.updateLineColors();
}

deleteRule(i: number) {
  if (!confirm('Do you want to delete this rule?')) return;
  this.boardRules.splice(i, 1);
  this.updateLineColors();
}
}